# Build Command:
# docker build -t bcollazo/catanatron-server:latest . -f Dockerfile.web
FROM python:3.12

WORKDIR /app

RUN pip install --upgrade pip

COPY . .
RUN pip install -e .[web]

EXPOSE 5001

ENV PYTHONUNBUFFERED=1

CMD ["gunicorn", "--bind", "0.0.0.0:5001", "--workers", "2", "--threads", "4", "--timeout", "120", "catanatron.web:create_app()"]
